name: Generate README from docs folder
on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate readme
        run: bash .github/workflows/generate-readme.sh
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update readme'
          add: 'README_AUTO.md'
          default_author: github_actions
